[unix_http_server]
file=/run/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
user=root
logfile=/dev/null
pidfile=/run/supervisord.pid
childlogdir=/tmp

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisor.sock

[program:dbus]
command=/usr/bin/dbus-daemon --system --nofork --nopidfile
user=root
priority=5
autostart=true
autorestart=true
startsecs=2
startretries=999
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:xvfb]
command=/usr/bin/Xvfb :99 -screen 0 %(ENV_RESOLUTION)sx24 -ac -nolisten tcp -noreset
user=streamer
priority=10
autostart=true
autorestart=true
startsecs=2
startretries=999
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:pulseaudio]
command=/usr/local/bin/run-pulseaudio
user=streamer
priority=10
autostart=true
autorestart=true
startsecs=2
startretries=999
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:openbox]
command=/usr/local/bin/run-openbox
user=streamer
priority=20
autostart=true
autorestart=true
startsecs=2
startretries=999
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:chromium]
command=/usr/bin/dbus-run-session -- /usr/local/bin/run-browser
user=streamer
priority=30
autostart=true
autorestart=true
startsecs=5
startretries=999
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:x11vnc]
command=/usr/local/bin/run-x11vnc
user=streamer
priority=30
autostart=true
autorestart=true
startsecs=2
startretries=999
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:novnc]
command=/usr/bin/websockify --web=/usr/share/novnc 0.0.0.0:6080 localhost:5900
user=streamer
priority=40
autostart=true
autorestart=true
startsecs=2
startretries=999
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:ffmpeg]
command=/usr/local/bin/run-ffmpeg
user=streamer
priority=40
autostart=true
autorestart=true
startsecs=2
startretries=999
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
